In [45]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv("text_emotion1.csv")

In [6]:
data.sample(5)

tweet_id sentiment          author  \
5921   1961092589   neutral   claireyjonesy   
7469   1961738862    relief  Hannah_gamblin   
1496   1957320299   neutral  MelodyAnnJones   
13462  1964039430   sadness        Sweeples   
24758  1694928130     worry       CWininsky   

                                                 content  
5921                             my hairs straight  lmao  
7469   is sooo close to finishing her exams  role on ...  
1496            Goodnight world! I have t o be up at 5am  
13462  Apparently it's 21 degrees in Kilkenny now! An...  
24758  is taking the dog to the vet then a play date ...

In [17]:
data['sentiment'].value_counts()

neutral       8638
worry         8459
happiness     5209
sadness       5165
love          3842
surprise      2187
fun           1776
relief        1526
hate          1323
empty          827
enthusiasm     759
boredom        179
anger          110
Name: sentiment, dtype: int64

In [48]:
print(data['content'])

0        @tiffanylue i know  i was listenin to bad habi...
1        Layin n bed with a headache  ughhhh...waitin o...
2                      Funeral ceremony...gloomy friday...
3                     wants to hang out with friends SOON!
4        @dannycastillo We want to trade with someone w...
                               ...                        
39995                                     @JohnLloydTaylor
39996                       Happy Mothers Day  All my love
39997    Happy Mother's Day to all the mommies out ther...
39998    @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...
39999    @mopedronin bullet train from tokyo    the gf ...
Name: content, Length: 40000, dtype: object


In [18]:
data_replace=data.copy()

In [20]:
data_replace

tweet_id   sentiment         author  \
0      1956967341       empty     xoshayzers   
1      1956967666     sadness      wannamama   
2      1956967696     sadness      coolfunky   
3      1956967789  enthusiasm    czareaquino   
4      1956968416     neutral      xkilljoyx   
...           ...         ...            ...   
39995  1753918954     neutral  showMe_Heaven   
39996  1753919001        love       drapeaux   
39997  1753919005        love       JenniRox   
39998  1753919043   happiness       ipdaman1   
39999  1753919049        love    Alpharalpha   

                                                 content  
0      @tiffanylue i know  i was listenin to bad habi...  
1      Layin n bed with a headache  ughhhh...waitin o...  
2                    Funeral ceremony...gloomy friday...  
3                   wants to hang out with friends SOON!  
4      @dannycastillo We want to trade with someone w...  
...                                                  ...  
39995                                   @JohnLloydTaylor  
39996                     Happy Mothers Day  All my love  
39997  Happy Mother's Day to all the mommies out ther...  
39998  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...  
39999  @mopedronin bullet train from tokyo    the gf ...  

[40000 rows x 4 columns]

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
data['sentiment_encoded']=LabelEncoder().fit_transform(data['sentiment'])

In [27]:
data

tweet_id   sentiment         author  \
0      1956967341       empty     xoshayzers   
1      1956967666     sadness      wannamama   
2      1956967696     sadness      coolfunky   
3      1956967789  enthusiasm    czareaquino   
4      1956968416     neutral      xkilljoyx   
...           ...         ...            ...   
39995  1753918954     neutral  showMe_Heaven   
39996  1753919001        love       drapeaux   
39997  1753919005        love       JenniRox   
39998  1753919043   happiness       ipdaman1   
39999  1753919049        love    Alpharalpha   

                                                 content  sentiment_encoded  
0      @tiffanylue i know  i was listenin to bad habi...                  2  
1      Layin n bed with a headache  ughhhh...waitin o...                 10  
2                    Funeral ceremony...gloomy friday...                 10  
3                   wants to hang out with friends SOON!                  3  
4      @dannycastillo We want to trade with someone w...                  8  
...                                                  ...                ...  
39995                                   @JohnLloydTaylor                  8  
39996                     Happy Mothers Day  All my love                  7  
39997  Happy Mother's Day to all the mommies out ther...                  7  
39998  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...                  5  
39999  @mopedronin bullet train from tokyo    the gf ...                  7  

[40000 rows x 5 columns]

In [33]:
encoder=LabelEncoder()
encoder.fit(data['sentiment'])
encoder.classes_

array(['anger', 'boredom', 'empty', 'enthusiasm', 'fun', 'happiness',
       'hate', 'love', 'neutral', 'relief', 'sadness', 'surprise',
       'worry'], dtype=object)

In [34]:
results=['anger', 'boredom', 'empty', 'enthusiasm', 'fun', 'happiness',
       'hate', 'love', 'neutral', 'relief', 'sadness', 'surprise',
       'worry']

In [40]:
count_vect=CountVectorizer()
count_vect.fit(data['content'].values)

CountVectorizer()

In [41]:
print("Print Vocabulary: "+str(count_vect.vocabulary_)+'\n\n')
print("Feature Names: "+str(count_vect.get_feature_names())+'\n\n')

Print Vocabulary: {'tiffanylue': 42934, 'know': 24017, 'was': 45848, 'listenin': 25463, 'to': 43187, 'bad': 4919, 'habit': 18430, 'earlier': 13732, 'and': 3374, 'started': 40270, 'freakin': 16431, 'at': 4404, 'his': 19455, 'part': 32220, 'layin': 24765, 'bed': 5497, 'with': 46653, 'headache': 18934, 'ughhhh': 44484, 'waitin': 45698, 'on': 31419, 'your': 47769, 'call': 7788, 'funeral': 16733, 'ceremony': 8464, 'gloomy': 17579, 'friday': 16548, 'wants': 45794, 'hang': 18641, 'out': 31753, 'friends': 16566, 'soon': 39574, 'dannycastillo': 11398, 'we': 45961, 'want': 45789, 'trade': 43584, 'someone': 39510, 'who': 46377, 'has': 18796, 'houston': 19873, 'tickets': 42894, 'but': 7511, 'no': 30630, 'one': 31425, 'will': 46516, 're': 34989, 'pinging': 33045, 'ghostridah14': 17347, 'why': 46439, 'didn': 12409, 'you': 47742, 'go': 17634, 'prom': 34089, 'bc': 5329, 'my': 29586, 'bf': 5816, 'like': 25240, 'should': 38404, 'be': 5353, 'sleep': 39005, 'im': 20487, 'not': 30807, 'thinking': 42692, 'a

In [50]:
ct=count_vect.fit_transform(data['content'].values)
print("The shape of the count is: "+str(ct.shape))
target=data['sentiment_encoded'].values
target

The shape of the count is: (40000, 48212)


array([ 2, 10, 10, ...,  7,  5,  7])

In [46]:
trans=TfidfTransformer()

In [52]:
train_counts=count_vect.fit_transform(data['content'].values)
train_data=trans.fit_transform(train_counts)
x_train,x_test,y_train,y_test=train_test_split(train_data,target,test_size=0.2,random_state=0)

In [53]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
model=mnb.fit(x_train,y_train)
preds=mnb.predict(x_test)
print(accuracy_score(y_test,preds)*100)
print(classification_report(y_test,preds))
print(confusion_matrix(y_test,preds))

28.512500000000003
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.00      0.00      0.00        37
           2       0.00      0.00      0.00       147
           3       0.00      0.00      0.00       147
           4       0.00      0.00      0.00       354
           5       0.45      0.08      0.14      1052
           6       0.00      0.00      0.00       251
           7       0.66      0.11      0.19       780
           8       0.31      0.43      0.36      1743
           9       0.00      0.00      0.00       292
          10       0.50      0.01      0.01      1062
          11       0.00      0.00      0.00       422
          12       0.26      0.80      0.39      1694

    accuracy                           0.29      8000
   macro avg       0.17      0.11      0.08      8000
weighted avg       0.31      0.29      0.20      8000

[[   0    0    0    0    0    0    0    0    5    0    0    

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [54]:
from sklearn.linear_model import LogisticRegression
rnb=LogisticRegression()
model2=rnb.fit(x_train,y_train)
pred2=rnb.predict(x_test)
print(accuracy_score(y_test,pred2)*100)
print(classification_report(y_test,pred2))
print(confusion_matrix(y_test,pred2))

35.8375
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.00      0.00      0.00        37
           2       0.00      0.00      0.00       147
           3       0.00      0.00      0.00       147
           4       0.16      0.01      0.03       354
           5       0.37      0.36      0.36      1052
           6       0.42      0.10      0.16       251
           7       0.55      0.38      0.45       780
           8       0.34      0.61      0.43      1743
           9       0.18      0.01      0.03       292
          10       0.39      0.26      0.31      1062
          11       0.16      0.02      0.03       422
          12       0.33      0.48      0.40      1694

    accuracy                           0.36      8000
   macro avg       0.22      0.17      0.17      8000
weighted avg       0.33      0.36      0.32      8000

[[   0    0    0    0    0    0    1    0   10    0    0    0    8]
 [ 

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [55]:
from sklearn.ensemble import RandomForestClassifier
rvc=RandomForestClassifier()
model3=rvc.fit(x_train,y_train)
pred3=rvc.predict(x_test)
print(accuracy_score(y_test,pred3)*100)
print(classification_report(y_test,pred3))
print(confusion_matrix(y_test,pred3))

32.775
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.00      0.00      0.00        37
           2       0.00      0.00      0.00       147
           3       0.00      0.00      0.00       147
           4       0.15      0.01      0.02       354
           5       0.36      0.25      0.30      1052
           6       0.34      0.09      0.14       251
           7       0.52      0.37      0.44       780
           8       0.31      0.61      0.41      1743
           9       0.21      0.01      0.02       292
          10       0.35      0.15      0.21      1062
          11       0.22      0.01      0.03       422
          12       0.30      0.48      0.37      1694

    accuracy                           0.33      8000
   macro avg       0.21      0.15      0.15      8000
weighted avg       0.31      0.33      0.28      8000

[[   0    0    0    0    0    1    0    1   10    0    0    0    7]
 [  

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [56]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier()
model4=knc.fit(x_train,y_train)
pred4=knc.predict(x_test)
print(accuracy_score(y_test,pred4)*100)
print(classification_report(y_test,pred4))
print(confusion_matrix(y_test,pred4))
report=classification_report(y_test,pred4)

23.4625
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.00      0.00      0.00        37
           2       0.02      0.01      0.01       147
           3       0.02      0.01      0.02       147
           4       0.07      0.03      0.04       354
           5       0.22      0.18      0.20      1052
           6       0.13      0.06      0.08       251
           7       0.33      0.22      0.26       780
           8       0.24      0.64      0.35      1743
           9       0.15      0.02      0.04       292
          10       0.23      0.11      0.15      1062
          11       0.06      0.01      0.02       422
          12       0.29      0.14      0.19      1694

    accuracy                           0.23      8000
   macro avg       0.13      0.11      0.10      8000
weighted avg       0.22      0.23      0.20      8000

[[   0    0    0    0    0    4    0    3    8    0    1    2    1]
 [ 

In [57]:
from sklearn.svm import SVC
spm=SVC(kernel='linear',decision_function_shape='ovr')
model5=spm.fit(x_train,y_train)
pred5=spm.predict(x_test)
print(accuracy_score(y_test,pred5)*100)
print(classification_report(y_test,pred5))
print(confusion_matrix(y_test,pred5))

35.85
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.00      0.00      0.00        37
           2       0.00      0.00      0.00       147
           3       0.00      0.00      0.00       147
           4       0.21      0.02      0.04       354
           5       0.36      0.40      0.38      1052
           6       0.36      0.13      0.19       251
           7       0.54      0.40      0.46       780
           8       0.34      0.58      0.43      1743
           9       0.24      0.02      0.03       292
          10       0.39      0.24      0.29      1062
          11       0.26      0.02      0.03       422
          12       0.34      0.49      0.40      1694

    accuracy                           0.36      8000
   macro avg       0.23      0.18      0.17      8000
weighted avg       0.34      0.36      0.32      8000

[[   0    0    0    0    0    1    1    1    6    1    1    0    8]
 [   

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
